language: csharp
dist: xenial
sudo: required
dotnet: 1.0.3
mono: none
script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test test/Kean.Tests.csproj --configuration Release
after_success:
  - dotnet pack src/ --configuration Release
  - dotnet nuget push *.nupkg --api-key $NUGET_API_KEY --source https://www.myget.org/F/kean/api/v2/package
notifications:
  email:
    on_success: never
    on_failure: always
