language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 1.0.0-preview2.1-003155
before_script:
  - chmod a+x ./tools/build.sh
  - chmod a+x ./tools/test.sh
  - chmod a+x ./tools/pack.sh
script:
  - ./tool/build.sh
  - ./tool/test.sh
after_success:
  - ./tool/pack.sh
notifications:
  email:
    on_success: never
    on_failure: always
